version: '3.1'

services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        HOST_NAME: postgres_db
    ports:
      - '3000:3000'
    depends_on:
      - postgres_db
    environment:
      - NODE_ENV=development
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=postgres_db
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=qwerty
      - TYPEORM_DATABASE=db
      - TYPEORM_PORT=5432
      - TYPEORM_SYNCHRONIZE=true
      - APP_PORT=3000
    volumes:
      - ../src:/usr/src/backend/src
  
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
